airPressure:
  _FillValue: -9999.9
  description: Air Pressure
  dims:
  - along_track
  - cross_track
  - range
  ndims: 3
  offset_scale: []
  path: VERENV/airPressure
  standard_name: airPressure
  units: hPa
airTemperature:
  _FillValue: -9999.9
  description: Air Temperature
  dims:
  - along_track
  - cross_track
  - range
  ndims: 3
  offset_scale: []
  path: VERENV/airTemperature
  standard_name: airTemperature
  units: K
cloudLiquidWater:
  _FillValue: -9999.9
  description: Cloud Liquid Water
  dims:
  - along_track
  - cross_track
  - range
  - nwater
  ndims: 3
  offset_scale: []
  path: VERENV/cloudLiquidWater
  standard_name: cloudLiquidWater
  units: kg/m^3
waterVapor:
  _FillValue: -9999.9
  description: waterVapor
  dims:
  - along_track
  - cross_track
  - range
  - nwater
  ndims: 4
  offset_scale: []
  path: VERENV/waterVapor
  standard_name: waterVapor
  units: kg/m^3
