cloudWaterPath:
  _FillValue: -9999.9
  description: Total integrated cloud liquid water in the vertical atmospheric column.
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: cloudWaterPath
  standard_name: cloudWaterPath
  units: kg/m^2
convectivePrecipitation:
  _FillValue: -9999.9
  description: The instantaneous convective precipitation rate at the surface
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: convectivePrecipitation
  standard_name: convectivePrecipitation
  units: mm/hr
frozenPrecipitation:
  _FillValue: -9999.9
  description: The instantaneous frozen precipitation rate at the surface
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: frozenPrecipitation
  standard_name: frozenPrecipitation
  units: mm/hr
iceWaterPath:
  _FillValue: -9999.9
  description: Total integrated ice water in the vertical atmospheric column.
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: iceWaterPath
  standard_name: iceWaterPath
  units: kg/m^2
mostLikelyPrecipitation:
  _FillValue: -9999.9
  description: The surface precipitation value with the closest Tb match within the
    Bayesian retrieval.
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: mostLikelyPrecipitation
  standard_name: mostLikelyPrecipitation
  units: mm/hr
pixelStatus:
  _FillValue: -99
  description: 'Explains the reason of no retrieval:

    0 : Valid pixel

    1 : Invalid Latitude / Longitude

    2 : Channel Tbs out of range

    3 : Surface code / histogram mismatch

    4 : Missing TCWV, T2m, or sfccode from preprocessor

    5 : No Bayesian Solution'
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: pixelStatus
  standard_name: pixelStatus
  units: '-'
probabilityOfPrecip:
  _FillValue: -99
  description: 'A diagnostic variable, in percent, defining the fraction of raining
    vs. non-raining Database

    profiles that make up the final solution. Values range from 0 to 100 percent.'
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: probabilityOfPrecip
  standard_name: probabilityOfPrecip
  units: '-'
qualityFlag:
  _FillValue: -99
  description: "Generalized quality of the retrieved pixel:\n                    \
    \     0 : Pixel is \"good\" and has the highest confidence of the best retrieval.\n\
    1 : Use with caution.\" Pixels can be set to 1 for the following reasons:\n  \
    \  - Sunglint is present, RFI, geolocate, warm load or other L1C \u2019positive\
    \ value\u2019 quality warning flags.\n    - All sea-ice covered surfaces.\n  \
    \  - All snow covered surfaces.\n    - Sensor channels are missing, but not critical\
    \ ones.\n2 : Use pixel with extreme care over snow covered surface.\"\n3 : Use\
    \ with extreme caution. Critical channels missing for the retrieval. "
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: qualityFlag
  standard_name: qualityFlag
  units: '-'
rainWaterPath:
  _FillValue: -9999.9
  description: Total integrated rain water in the vertical atmospheric column.
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: rainWaterPath
  standard_name: rainWaterPath
  units: kg/m^2
sunGlintAngle:
  _FillValue: -99
  description: " The angle between the sun and the instrument view direction as reflected\n\
    off the Earth\u2019s surface. sunGlintAngle is the angular separation between\
    \ the reflected\nsatellite view vector and the sun vector. When sunGlintAngle\
    \ is zero, the instrument\nviews the center of the specular (mirror-like) sun\
    \ reflection. If this angle is less than ten\ndegrees, the pixel is affected by\
    \ sunglint and the pixel\u2019s qualityFlag is lowered to 1. Values\nrange from\
    \ 0 to 127 degrees."
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: sunGlintAngle
  standard_name: sunGlintAngle
  units: '-'
surfacePrecipitation:
  _FillValue: -9999.9
  description: The instantaneous precipitation rate at the surface
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: surfacePrecipitation
  standard_name: surfacePrecipitation
  units: mm/hr
surfaceTypeIndex:
  _FillValue: -99
  description: " Surface type:\n                        1 : Ocean\n              \
    \          2 : Sea-Ice\n                        3-7 : Decreasing vegetation\n\
    \                        8-11 : Decreasing snow cover\n                      \
    \  12 : Standing Water\n                        13 : Land/ocean or water Coast\n\
    \                        14 : Sea-ice edge "
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: surfaceTypeIndex
  standard_name: surfaceTypeIndex
  units: '-'
